<?php
/*
+--------------------------------------------------------------------------
|   WeCenter [#RELEASE_VERSION#]
|   ========================================
|   by WeCenter Software
|   © 2011 - 2014 WeCenter. All Rights Reserved
|   http://www.wecenter.com
|   ========================================
|   Support: WeCenter@qq.com
|
+---------------------------------------------------------------------------
*/
if (! defined('IN_ANWSION'))
{
    die();
}
class home extends AWS_MOBILE_CONTROLLER
{
    public function get_access_rule()
    {
        $rule_action['rule_type'] = 'white'; //黑名单,黑名单中的检查  'white'白名单,白名单以外的检查
        $rule_action['actions'] = array();
        return $rule_action;
    }

    public function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub
        if (!is_mobile())
        {
            HTTP::redirect('/home/');
        }
    }

    /*我的动态*/
    public function index_action()
    {
        TPL::output('m/home/index');
    }

    /*我的关注*/
    public function focus_action()
    {
        TPL::output('m/home/focus');
    }

    /*我的积分*/
    public function integral_action()
    {
        $income = $this->model('integral')->sum('integral_log','integral','integral > 0 AND uid = ' . $this->user_id);
        TPL::assign('income',$income);
        TPL::output('m/home/integral');
    }

    /*我的草稿*/
    public function draft_action()
    {
        TPL::output('m/home/draft');
    }

    /*我的收藏*/
    public function favorite_action()
    {
        TPL::assign('favorite_tags', $this->model('favorite')->get_favorite_tags($this->user_id));
        TPL::output('m/home/favorite');
    }
}
